package org.hfly.app.persondisk.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.hfly.app.persondisk.domain.DiskFile;
import org.hfly.app.persondisk.domain.DiskFileExample;

public interface DiskFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_filelist
     *
     * @mbg.generated
     */
    long countByExample(DiskFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_filelist
     *
     * @mbg.generated
     */
    int deleteByExample(DiskFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_filelist
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_filelist
     *
     * @mbg.generated
     */
    int insert(DiskFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_filelist
     *
     * @mbg.generated
     */
    int insertSelective(DiskFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_filelist
     *
     * @mbg.generated
     */
    List<DiskFile> selectByExampleWithBLOBs(DiskFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_filelist
     *
     * @mbg.generated
     */
    List<DiskFile> selectByExample(DiskFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_filelist
     *
     * @mbg.generated
     */
    DiskFile selectByPrimaryKey(Long fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_filelist
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DiskFile record, @Param("example") DiskFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_filelist
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") DiskFile record, @Param("example") DiskFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_filelist
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DiskFile record, @Param("example") DiskFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_filelist
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DiskFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_filelist
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(DiskFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_filelist
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DiskFile record);
}