package org.hfly.app.persondisk.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.hfly.app.persondisk.domain.InviteCode;
import org.hfly.app.persondisk.domain.InviteCodeExample;

public interface InviteCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_invitecode
     *
     * @mbg.generated
     */
    long countByExample(InviteCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_invitecode
     *
     * @mbg.generated
     */
    int deleteByExample(InviteCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_invitecode
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer icid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_invitecode
     *
     * @mbg.generated
     */
    int insert(InviteCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_invitecode
     *
     * @mbg.generated
     */
    int insertSelective(InviteCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_invitecode
     *
     * @mbg.generated
     */
    List<InviteCode> selectByExample(InviteCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_invitecode
     *
     * @mbg.generated
     */
    InviteCode selectByPrimaryKey(Integer icid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_invitecode
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") InviteCode record, @Param("example") InviteCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_invitecode
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") InviteCode record, @Param("example") InviteCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_invitecode
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InviteCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_invitecode
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InviteCode record);
}