package org.hfly.app.persondisk.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.hfly.app.persondisk.domain.Permisson;
import org.hfly.app.persondisk.domain.PermissonExample;

public interface PermissonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_permission
     *
     * @mbg.generated
     */
    long countByExample(PermissonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_permission
     *
     * @mbg.generated
     */
    int deleteByExample(PermissonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_permission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_permission
     *
     * @mbg.generated
     */
    int insert(Permisson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_permission
     *
     * @mbg.generated
     */
    int insertSelective(Permisson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_permission
     *
     * @mbg.generated
     */
    List<Permisson> selectByExample(PermissonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_permission
     *
     * @mbg.generated
     */
    Permisson selectByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_permission
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Permisson record, @Param("example") PermissonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_permission
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Permisson record, @Param("example") PermissonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Permisson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Permisson record);
}