package org.hfly.app.persondisk.domain;

import java.io.Serializable;

public class DiskFile implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_filelist.fid
     *
     * @mbg.generated
     */
    private Long fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_filelist.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_filelist.fileName
     *
     * @mbg.generated
     */
    private String filename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_filelist.size
     *
     * @mbg.generated
     */
    private Long size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_filelist.lastModifyTime
     *
     * @mbg.generated
     */
    private Long lastmodifytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_filelist.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_filelist.path
     *
     * @mbg.generated
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table d_filelist
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_filelist.fid
     *
     * @return the value of d_filelist.fid
     *
     * @mbg.generated
     */
    public Long getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_filelist.fid
     *
     * @param fid the value for d_filelist.fid
     *
     * @mbg.generated
     */
    public void setFid(Long fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_filelist.uid
     *
     * @return the value of d_filelist.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_filelist.uid
     *
     * @param uid the value for d_filelist.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_filelist.fileName
     *
     * @return the value of d_filelist.fileName
     *
     * @mbg.generated
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_filelist.fileName
     *
     * @param filename the value for d_filelist.fileName
     *
     * @mbg.generated
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_filelist.size
     *
     * @return the value of d_filelist.size
     *
     * @mbg.generated
     */
    public Long getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_filelist.size
     *
     * @param size the value for d_filelist.size
     *
     * @mbg.generated
     */
    public void setSize(Long size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_filelist.lastModifyTime
     *
     * @return the value of d_filelist.lastModifyTime
     *
     * @mbg.generated
     */
    public Long getLastmodifytime() {
        return lastmodifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_filelist.lastModifyTime
     *
     * @param lastmodifytime the value for d_filelist.lastModifyTime
     *
     * @mbg.generated
     */
    public void setLastmodifytime(Long lastmodifytime) {
        this.lastmodifytime = lastmodifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_filelist.state
     *
     * @return the value of d_filelist.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_filelist.state
     *
     * @param state the value for d_filelist.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_filelist.path
     *
     * @return the value of d_filelist.path
     *
     * @mbg.generated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_filelist.path
     *
     * @param path the value for d_filelist.path
     *
     * @mbg.generated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_filelist
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DiskFile other = (DiskFile) that;
        return (this.getFid() == null ? other.getFid() == null : this.getFid().equals(other.getFid()))
            && (this.getUid() == null ? other.getUid() == null : this.getUid().equals(other.getUid()))
            && (this.getFilename() == null ? other.getFilename() == null : this.getFilename().equals(other.getFilename()))
            && (this.getSize() == null ? other.getSize() == null : this.getSize().equals(other.getSize()))
            && (this.getLastmodifytime() == null ? other.getLastmodifytime() == null : this.getLastmodifytime().equals(other.getLastmodifytime()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()))
            && (this.getPath() == null ? other.getPath() == null : this.getPath().equals(other.getPath()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_filelist
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getFid() == null) ? 0 : getFid().hashCode());
        result = prime * result + ((getUid() == null) ? 0 : getUid().hashCode());
        result = prime * result + ((getFilename() == null) ? 0 : getFilename().hashCode());
        result = prime * result + ((getSize() == null) ? 0 : getSize().hashCode());
        result = prime * result + ((getLastmodifytime() == null) ? 0 : getLastmodifytime().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        result = prime * result + ((getPath() == null) ? 0 : getPath().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_filelist
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", fid=").append(fid);
        sb.append(", uid=").append(uid);
        sb.append(", filename=").append(filename);
        sb.append(", size=").append(size);
        sb.append(", lastmodifytime=").append(lastmodifytime);
        sb.append(", state=").append(state);
        sb.append(", path=").append(path);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}