package org.hfly.app.persondisk.domain;

import java.io.Serializable;

public class InviteCode implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_invitecode.icid
     *
     * @mbg.generated
     */
    private Integer icid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_invitecode.inviteCode
     *
     * @mbg.generated
     */
    private String invitecode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_invitecode.permission
     *
     * @mbg.generated
     */
    private Integer permission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_invitecode.ownerUserId
     *
     * @mbg.generated
     */
    private Integer owneruserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_invitecode.userId
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_invitecode.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table d_invitecode
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_invitecode.icid
     *
     * @return the value of d_invitecode.icid
     *
     * @mbg.generated
     */
    public Integer getIcid() {
        return icid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_invitecode.icid
     *
     * @param icid the value for d_invitecode.icid
     *
     * @mbg.generated
     */
    public void setIcid(Integer icid) {
        this.icid = icid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_invitecode.inviteCode
     *
     * @return the value of d_invitecode.inviteCode
     *
     * @mbg.generated
     */
    public String getInvitecode() {
        return invitecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_invitecode.inviteCode
     *
     * @param invitecode the value for d_invitecode.inviteCode
     *
     * @mbg.generated
     */
    public void setInvitecode(String invitecode) {
        this.invitecode = invitecode == null ? null : invitecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_invitecode.permission
     *
     * @return the value of d_invitecode.permission
     *
     * @mbg.generated
     */
    public Integer getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_invitecode.permission
     *
     * @param permission the value for d_invitecode.permission
     *
     * @mbg.generated
     */
    public void setPermission(Integer permission) {
        this.permission = permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_invitecode.ownerUserId
     *
     * @return the value of d_invitecode.ownerUserId
     *
     * @mbg.generated
     */
    public Integer getOwneruserid() {
        return owneruserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_invitecode.ownerUserId
     *
     * @param owneruserid the value for d_invitecode.ownerUserId
     *
     * @mbg.generated
     */
    public void setOwneruserid(Integer owneruserid) {
        this.owneruserid = owneruserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_invitecode.userId
     *
     * @return the value of d_invitecode.userId
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_invitecode.userId
     *
     * @param userid the value for d_invitecode.userId
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_invitecode.state
     *
     * @return the value of d_invitecode.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_invitecode.state
     *
     * @param state the value for d_invitecode.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_invitecode
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        InviteCode other = (InviteCode) that;
        return (this.getIcid() == null ? other.getIcid() == null : this.getIcid().equals(other.getIcid()))
            && (this.getInvitecode() == null ? other.getInvitecode() == null : this.getInvitecode().equals(other.getInvitecode()))
            && (this.getPermission() == null ? other.getPermission() == null : this.getPermission().equals(other.getPermission()))
            && (this.getOwneruserid() == null ? other.getOwneruserid() == null : this.getOwneruserid().equals(other.getOwneruserid()))
            && (this.getUserid() == null ? other.getUserid() == null : this.getUserid().equals(other.getUserid()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_invitecode
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getIcid() == null) ? 0 : getIcid().hashCode());
        result = prime * result + ((getInvitecode() == null) ? 0 : getInvitecode().hashCode());
        result = prime * result + ((getPermission() == null) ? 0 : getPermission().hashCode());
        result = prime * result + ((getOwneruserid() == null) ? 0 : getOwneruserid().hashCode());
        result = prime * result + ((getUserid() == null) ? 0 : getUserid().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_invitecode
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", icid=").append(icid);
        sb.append(", invitecode=").append(invitecode);
        sb.append(", permission=").append(permission);
        sb.append(", owneruserid=").append(owneruserid);
        sb.append(", userid=").append(userid);
        sb.append(", state=").append(state);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}